#!/bin/bash
#
# This script installs shortcut commands for the Data Science Toolkit scripts.
# You can see full documentation at http://www.datasciencetoolkit.org/developerdocs

pushd `dirname $0` > /dev/null
CURRENT_DIR=`pwd`
popd > /dev/null

#COMMAND="ln -s "
COMMAND="cp "

INSTALL_DIR=/usr/bin

rm -f ${INSTALL_DIR}/dstk.py
${COMMAND} ${CURRENT_DIR}'/dstk.py' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/ip2coordinates
${COMMAND} ${CURRENT_DIR}'/ip2coordinates' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/street2coordinates
${COMMAND} ${CURRENT_DIR}'/street2coordinates' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/coordinates2politics
${COMMAND} ${CURRENT_DIR}'/coordinates2politics' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/text2places
${COMMAND} ${CURRENT_DIR}'/text2places' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/file2text
${COMMAND} ${CURRENT_DIR}'/file2text' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/text2sentences
${COMMAND} ${CURRENT_DIR}'/text2sentences' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/html2text
${COMMAND} ${CURRENT_DIR}'/html2text' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/html2story
${COMMAND} ${CURRENT_DIR}'/html2story' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/text2people
${COMMAND} ${CURRENT_DIR}'/text2people' ${INSTALL_DIR}/

rm -f ${INSTALL_DIR}/text2times
${COMMAND} ${CURRENT_DIR}'/text2times' ${INSTALL_DIR}/
